name: danbooru_dart
description: A starting point for Dart libraries or applications.
version: 0.0.3
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  xml: ^6.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
